using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Channels;
using System.Threading.Tasks;
using Telegram_bot.Class;
using TL;
using WTelegram;
await authorization.Main();
Console.ReadLine();